# A demo explanation on how to use meta-arguments in Terraform.

# List itration example
variable "bucket_names" {
    description = "List of S3 bucket names to create"
    type = list(string)
    default = [ "my-unique-bucket-jatin-v1-alpha-v1", "my-unique-bucket-jatin-v2-beta" ]
  
}

variable "bucket_set" {
    description = "Set of S3 bucket names to create"
    type = set(string)
    default = [ "my-unique-bucket-jatin-v1-alpha-v1", "my-unique-bucket-jatin-v2-beta" ]
}

resource "aws_s3_bucket" "buckets" {
    # starting is 0 till end -1 , i.e 0,1
    count = 2
    bucket = var.bucket_names[count.index]               # count example

    # for_each = var.bucket_names                        # for_each example
}

# Set itration example, uses lenght, without any order, but unique keys are generated by terraform itself
resource "aws_s3_bucket" "buckets2" {
    for_each = var.bucket_set
    bucket = each.value  

    depends_on = [ aws_s3_bucket.buckets ]               # depends on example 
    
}